import {StyleSheet, Dimensions, Platform} from 'react-native';
const {height, width} = Dimensions.get('window');

export const MovieStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#0C0C0C',
  },
  logo: {
    width: width * 0.43,
    height: height * 0.0425,
    marginTop: height * 0.01,
    marginLeft: width * 0.02,
  },
  logo1: {
    width: width * 0.2,
    height: height * 0.06,
    marginTop: height * 0.01,
    marginLeft: width * 0.02,
  },
  viewAll: {
    position: 'absolute',
    fontFamily: 'space_mono_regular',
    color: 'navy',
    left: width * 0.73,
    bottom: 1,
  },
  text: {
    fontFamily: 'godofwar',
    color: 'white',
    fontSize: height * 0.021,
    marginBottom: height * 0.017,
    marginLeft: width * 0.02,
    marginTop: height * 0.011,
  },
  image: {
    borderRadius: 10,
    height: height * 0.3,
    width: width - 10,
    marginLeft: 5,
  },
  searchIcon: {
    position: 'absolute',
    right: width * 0.05,
    top: height * 0.015,
  },
});
export const styles = StyleSheet.create({
  imageContainer: {
    marginBottom: Platform.select({ios: 0, android: 1}), // Prevent a random Android rendering issue
    backgroundColor: '#151515',
    borderRadius: 5,
    width: width * 0.95,
    height: height * 0.25,
  },
  text: {
    fontFamily: 'batman',
    fontSize: height * 0.018,
    color: 'white',
    marginTop: height * 0.01,
  },
  text2: {
    color: 'powderblue',
    fontSize: height * 0.025,
    marginBottom: height * 0.015,
    fontFamily: 'space_mono_regular',
  },
  image: {
    ...StyleSheet.absoluteFillObject,
    resizeMode: 'contain',
    backgroundColor: 'black',
    borderRadius: 5,
    width: width * 0.95,
    height: height * 0.25,
  },
  button: {
    marginTop: height * 0.06,
    backgroundColor: '#2A2D2F',
    flexDirection: 'row',
    alignItems: 'center',
    width: width * 0.8,
    borderRadius: 5,
    height: height * 0.07,
    justifyContent: 'space-around',
    alignSelf: 'center',
  },
  socialIcon: {
    width: width * 0.12,
    marginRight: width * 0.09,
    height: height * 0.07,
    borderRadius: 5,
  },
  image2: {
    resizeMode: 'contain',
    width: width * 0.32,
    height: height * 0.23,
    borderRadius: 5,
  },
});

export const PreviewStyles = StyleSheet.create({
  image: {
    height: height * 0.77,
    borderBottomRightRadius: height * 0.02,
    borderBottomLeftRadius: height * 0.02,
    width: width,
  },
  trailer: {
    position: 'absolute',
    zIndex: 3,
    left: 0,
    borderBottomRightRadius: width * 0.7,
    borderBottomLeftRadius: width * 0.04,
    width,
    height: height * 0.43,
  },
  share: {
    right: width * 0.02,
    zIndex: 2,
    position: 'absolute',
    top: height * 0.71,
    marginRight: width * 0.05,
  },
  addButtonSmall: {
    backgroundColor: '#5b310a',
    alignItems: 'center',
    width: width * 0.085,
    justifyContent: 'center',
    borderWidth: 0,
    height: height * 0.055,
  },
  preview: {
    color: 'white',
    top: height * 0.72,
    position: 'absolute',
    right: width * 0.02,
    fontFamily: 'godofwar',
    zIndex: 3,
    fontSize: height * 0.025,
  },
  downMenu: {
    left: width * 0.028,
    top: height * 0.645,
    position: 'absolute',
    zIndex: 1,
    flexDirection: 'row',
  },
  back: {
    zIndex: 5,
    position: 'absolute',
    left: width * 0.03,
    top: height * 0.015,
    backgroundColor: 'black',
    borderRadius: 100,
  },
  logo: {
    height: height * 0.03,
    width: width * 0.3,
    position: 'absolute',
    zIndex: 4,
    right: 5,
  },
  play: {
    backgroundColor: "#0c0c0c",
    alignSelf: 'center',
    top: height * 0.35,
    zIndex: 2,
    borderRadius: 100,
    position: 'absolute',
  },
  imdb: {
    width: width * 0.1,
    height: height * 0.025,
    marginTop: height * 0.01,
    marginLeft: width * 0.02,
    borderRadius: width * 0.006,
  },
  close: {
    top: height * 0.04,
    right: width * 0.03,
    position: 'absolute',
    zIndex: 4,
    backgroundColor: 'black',
    borderRadius: 100,
  },
  genreView: {
    position: 'absolute',
    zIndex: 2,
    top: height * 0.53,
    flexDirection: 'row',
    paddingLeft: width * 0.02,
    paddingRight: width * 0.026,
    flexWrap: 'wrap',
  },
  genreText: {
    fontSize: height * 0.022,
    marginRight: width * 0.01,
    marginLeft: width * 0.01,
    fontFamily: 'space_mono_regular',
    color: 'white',
  },
  genreButton: {
    marginBottom: height * 0.015,
    backgroundColor: '#371B58',
    borderRadius: width * 0.027,
    alignContent: 'center',
    borderWidth: width * 0.01,
    borderColor: 'purple',
    marginRight: width * 0.03,
  },
  text: {
    paddingRight: 5,
    fontFamily: 'batman',
    fontSize: height * 0.023,
    marginTop: height * 0.015,
    color: 'white',
  },
  synopsis: {
    marginTop: -5,
    fontFamily: 'space_mono_regular',
    paddingLeft: width * 0.025,
    paddingRight: 5,
    textAlign: 'left',
    fontSize: height * 0.0215,
    marginBottom: width * 0.04,
    color: 'white',
  },
  text2: {
    marginTop: height * 0.03,
    marginBottom: height * 0.02,
    paddingLeft: width * 0.013,
    fontFamily: 'batman',
    color: 'white',
    fontSize: height * 0.02,
  },
  refresh: {
    zIndex: 5,
    position: 'absolute',
    left: width * 0.47,
    top: height * 0.2,
  },
  addButton: {
    position: 'absolute',
    zIndex: 1,
    borderColor: '#5b310a',
    borderWidth: 3,
    borderRadius: width * 0.023,
    left: width * 0.028,
    top: height * 0.71,
    width: width * 0.44,
    height: height * 0.052,
  },
  gradient: {
    top: 0,
    position: 'absolute',
    width: '100%',
    height: height * 0.8,
    opacity: 0.75,
  },
  title: {
    fontFamily: 'batman',
    fontSize: height * 0.023,
    paddingLeft: width * 0.02,
    paddingRight: 5,
    marginTop: height * 0.01,
    color: 'white',
    zIndex: 3,
  },
  tagline: {
    fontSize: height * 0.04,
    fontFamily: 'space_mono_regular',
    color: 'white',
    paddingRight: width * 0.02,
    marginTop: height * 0.003,
    marginBottom: height * 0.01,
    marginLeft: width * 0.02,
    zIndex: 3,
  },
  streamButton: {
    justifyContent: 'center',
    width: width * 0.456,
    height: height * 0.06,
    position: 'absolute',
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: '#5b310a',
    borderRadius: 5,
    zIndex: 2,
    top: height * 0.28,
    left: width * 0.52,
  },
  streamButton1: {
    justifyContent: 'center',
    width: width * 0.4,
    height: height * 0.06,
    position: 'absolute',
    alignSelf: 'center',
    alignItems: 'center',
    backgroundColor: '#ffff',
    borderRadius: 5,
    zIndex: 2,
    top: height * 0.28,
    left: width * 0.03,
  },
});

export const ListStyles = StyleSheet.create({
  item: {
    width: width * 0.31,
    height: height * 0.23,
  },
  image: {
    width: width * 0.31,
    height: height * 0.23,
    borderRadius: 5,
    resizeMode: 'contain',
  },
  close: {
    position: 'absolute',
    zIndex: 1,
    borderRadius: 100,
    top: height * 0.457,
    left: width * 0.88,
    backgroundColor: '#0c0c0c',
  },
});
